# Generated by Django 3.0.7 on 2020-06-22 20:28

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('creationTime', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedTime', models.DateTimeField(auto_now=True)),
                ('userHandle', models.CharField(max_length=30, unique=True)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('loginId', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('mobileNumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('dateOfBirth', models.DateField(null=True)),
                ('verificationLevel', models.CharField(choices=[('U', 'Unverified'), ('V', 'Verified'), ('O', 'Official')], max_length=1)),
                ('karma', models.IntegerField(default=0)),
                ('followers_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('post_count', models.IntegerField(default=0)),
                ('accountDisabled', models.BooleanField(default=False)),
                ('accountDeleted', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender'), ('S', 'Prefer not to say')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('F', 'Follow'), ('U', 'Unfollow'), ('B', 'Block'), ('M', 'Mute'), ('FR', 'Follow Requested')], max_length=2)),
                ('userIdFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='users.User')),
                ('userIdTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='users.User')),
            ],
        ),
    ]
