version: '3'

services:
  backend:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: ccp-backend-brain
    volumes:
      - .:/usr/src/ccp-backend-brain
    ports:
      - "8000:8000"